services:
  backend:
    build: ./Backend
    ports:
      - "18082:8082"   # backend 1XXXX
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=1234
      - DB_NAME=money_db
      - DB_PORT=23306  # ใช้ MySQL (2XXXX)
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: money_db
    ports:
      - "23306:3306"   # mysql 2XXXX
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "18080:80"   # phpmyadmin 1XXXX
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 1234
      PMA_ARBITRARY: 1
    depends_on:
      - db

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 261146
      POSTGRES_DB: Money
    ports:
      - "25432:5432"   # postgres 2XXXX
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:   # ✅ ย้ายเข้ามาใน services
    image: dpage/pgadmin4
    restart: always
    ports:
      - "18081:80"   # web UI ของ pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

volumes:
  db_data:
  postgres_data:
