version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"          # phpMyAdmin ต้องรันบน HTTP port เช่น 8080
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root        # ตั้ง user auto-login
      PMA_PASSWORD: root    # รหัสผ่าน auto-login
      PMA_ARBITRARY: 1      # อนุญาต connection แบบ arbitrary
    depends_on:
      - db

volumes:
  db_data:
